name = "voice-gateway"
main = "dist/index.html"
compatibility_date = "2024-03-12"

[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "npm run build"
output_dir = "dist"
[build.environment]
NODE_VERSION = "18.18.0"

[build.upload]
format = "service-worker" 